services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Strong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./docker/init.sql:/docker/init.sql
      - ./docker/entrypoint.sh:/docker/entrypoint.sh
    entrypoint: /bin/bash /docker/entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Strong!Passw0rd' -Q 'SELECT 1' -No"]
      interval: 5s
      timeout: 5s
      retries: 10
