-- Schema (matches EF Core / Npgsql output)
CREATE TABLE IF NOT EXISTS "Departments" (
    "Id"      integer GENERATED BY DEFAULT AS IDENTITY,
    "Street"  text NOT NULL,
    "City"    text NOT NULL,
    "ZipCode" text NOT NULL,
    CONSTRAINT "PK_Departments" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Employees" (
    "Id"          integer GENERATED BY DEFAULT AS IDENTITY,
    "Name"        text NOT NULL,
    "Email"       text NOT NULL,
    "DepartmentId" integer NULL,
    CONSTRAINT "PK_Employees" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Employees_Departments_DepartmentId"
        FOREIGN KEY ("DepartmentId")
        REFERENCES "Departments" ("Id")
        ON DELETE SET NULL
);

-- Seed data
INSERT INTO "Departments" ("Id", "Street", "City", "ZipCode") VALUES
    (1, 'Main Street',  'Springfield', '12345'),
    (2, 'Elm Street',   'Shelbyville', '54321'),
    (3, 'Oak Avenue',   'Ogdenville',  '67890');

INSERT INTO "Employees" ("Id", "Name", "Email", "DepartmentId") VALUES
    (1, 'John Doe',       'john.doe@example.com',       1),
    (2, 'Jane Smith',     'jane.smith@example.com',     2),
    (3, 'Alice Johnson',  'alice.johnson@example.com',  3);

-- Advance sequences so EF Core / test inserts don't collide with seeded IDs
SELECT setval(pg_get_serial_sequence('"Departments"', 'Id'), MAX("Id")) FROM "Departments";
SELECT setval(pg_get_serial_sequence('"Employees"',  'Id'), MAX("Id")) FROM "Employees";
