<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTestProject>true</IsTestProject>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApp\WebApp.csproj" />
    <ProjectReference Include="..\E2ETests.Shared\E2ETests.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="xunit.v3" Version="3.2.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageReference Include="Microsoft.Playwright" Version="1.59.0" />
  </ItemGroup>

</Project>
